require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'CropRegistration' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false
  )

  target 'CropRegistrationTests' do
    inherit! :complete
    # Pods for testing
  end

  # ——— Make sure this is indented _inside_ your target ———
  use_flipper!({ 'Flipper-Folly' => '2.5.3', 
                 'Flipper'       => '0.87.0', 
                 'Flipper-RSocket'=> '1.3.1' })

  # ——— Only _one_ post_install block, merging both needs ———
  post_install do |installer|
    react_native_post_install(installer)

    installer.generated_projects.each do |project|
      project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
        end
      end
    end
  end
end
